### ISSUE TITLE
Bubble sort accessing an undefined value

### ISSUE THREAD

**Issue by mmrazik** [ElaMoscicka/Pet-projects#1]
Hi Ela,
Awesome job so I thought I'll create your first bug (as that is what most developers deal with anyway :))!

Your BubbleSort implementation has a minor bug which has no effect on the end result because of how JS works. It would be a problem in other languages, though.

These two lines are problematic:

>     for (var i = 0; i < numbers.length; i++) {
>      if (numbers[i] > numbers[i + 1]) 

Let's assume numbers looks like `[4, 3, 2, 1]`.
`numbers.length` is `4`.
In the very last iteration of the for loop, `i` equals `3` (as that is the last number `< numbers.length`).
The `if` statement is then actually comparing `numbers[3] > numbers[4]`. However, `numbers[4]` is undefined (as that would be the 5th element in the array while the array only has 4 elements).

In this case you will compare integer (`number[3]`) with `undefined` which in JS evaluates to `false` so nothing happens and your code works. It is still a bug, though (which almost everybody does in this case)  :)

**Comment by ElaMoscicka** [comment]
Hi,
thanks for having a look at my code and for noticing this bug, I'll make improvements ;)
Ela

**Comment by ElaMoscicka** [comment]
ok, changes made, hope now is ok;)

**Comment by mmrazik** [comment]
Indeed. Looks good.
